### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by B3L7** [samme/phaser-plugin-game-scale#1]
Thank you for making this.

I am having issue getting this to work with webpack. I'm importing like this:

```
import 'phaser';
import ControlPlugin from './plugins/control';
import GameScalePlugin from './plugins/GameScalePlugin';
import BootScene from './scenes/BootScene'
import PreloadScene from './scenes/PreloadScene'
import StageScene from './scenes/StageScene'

const config = {
	type: Phaser.AUTO,
	parent: 'wrapper',
	width: 800,
	height: 600,
	scaleMode: 0,
	pixelArt: true,
	clearBeforeRender: false,
	physics: {
		default: 'matter',
		matter: {
			gravity: { y: 1 },
			debug: false,
			enableSleep: false
		}
	},
	plugins: {
		scene: [
			{ key: 'ControlPlugin', plugin: ControlPlugin, mapping: 'Controls' }
		],
		global: [
			{ key: 'GameScalePlugin', plugin: GameScalePlugin, mapping: 'gameScale' }
		]
	},
	scene: [
		BootScene,
		PreloadScene,
		StageScene
	]
};

const game = new Phaser.Game(config);
```

I can see the plugin in the bundle but it isn't getting mapped to the scenes.

**Comment by samme** [comment]
Check if `game.plugins.get('GameScalePlugin')` exists.

You can step through Phaser.Plugins.PluginManager#addToScene. That's where the mapping should be applied.

Any console warnings?

**Comment by samme** [comment]
I cloned phaser3-project-template](https://github.com/photonstorm/phaser3-project-template) and added the plugin, it worked. <https://gist.github.com/samme/8f9353e8c6e0848ce7f9ad8ebdb8a211>

**Comment by B3L7** [comment]
Got it. I'm using typescript so I had to change it to:

`const GameScalePlugin = require(path to plugin);`

Thanks again for your help and your excellent plugin!
